### PR TITLE
#117: UCP tab is not updated in migration

### LINKED ISSUE #117: UCP tab is not updated in migration
As pointed in [this comment](https://www.phpbb.com/customise/db/extension/ads/support/topic/186906?p=619666#p619666), UCP tab auth is not updated because we call `custom` wrongly in migration.

### PR DESCRIPTION
**Pull request by senky**
Fixes #117

### CODE REVIEW

File: migrations/v10x/m12_u_phpbb_ads_permission.php [hunk 1]
```diff
@@ -35,6 +35,8 @@ public function update_data()
 			array('permission.add', array('u_phpbb_ads')),
 			array('custom', array(
 				array($this, 'set_u_phpbb_ads_permission'),
```
Comment (VSEphpbb) [inline migrations/v10x/m12_u_phpbb_ads_permission.php]: These can be without the extra line breaks.
